### ISSUE TITLE
dirname( __FILE__ ) doesn't work when command is bundled into Phar

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/config-command#3]
```
Warning: file_get_contents(phar://wp-cli.phar/templates/phar:///tmp/wp-cli-phar/wp/vendor/wp-cli/config-command/templates/wp-config.mustache): failed to open stream: phar error: "templates/phar:/tmp/wp-cli-phar/wp/vendor/wp-cli/config-command/templates/wp-config.mustache" is not a file in phar "wp-cli.phar" in phar:///tmp/wp-cli-phar/wp/php/utils.php on line 459
```

From https://travis-ci.org/wp-cli/wp-cli/jobs/219779320

**Comment by danielbachhuber** [comment]
@schlessera Does https://github.com/wp-cli/wp-cli/pull/3978/commits/8929f6c84fd707530a45aca31acf282f77a615c9 seem like a reasonable fix to you, or would you go further?

**Comment by schlessera** [comment]
Yes, looks reasonable enough. I think we should try to move forward as fast as possible with the major blocking issues to get everything into separate packages. We can always do things more elegantly down the road.

**Comment by danielbachhuber** [comment]
Ok. This was fixed with https://github.com/wp-cli/wp-cli/pull/3978

**Comment by ght** [comment]
I got the same error message with the latest version (v1.3.0) and after some debugging realized it was because the script downloaded the wp-cli phar and then tried installing in the same directory. Downloading the phar to a separate directory makes it work as expected again. Just thought I'd share in case others make the same mistake, since this is the top result for that error message.

Maybe a clearer error message should be added for this case. Especially because `wp core download` works fine, and only `wp core config ...` breaks.

**Comment by monperrus** [comment]
I confirm the diagnosis of @ght: the error comes when wp is in the current directory (`./wp`)

Moving wp-cli phar to another directory is a valid workaround.
